# Generated by Django 5.2.6 on 2025-09-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.center')),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telescopes', to='api.center')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('GRB', 'Gamma Ray Burst'), ('SN', 'Supernova'), ('GW', 'Gravitational Wave'), ('NU', 'Neutrino')], max_length=10)),
                ('discovery_date', models.DateField(blank=True, help_text="Date de découverte de l'événement", null=True)),
                ('observation_date', models.DateTimeField(blank=True, help_text="Date d'observation par le télescope", null=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.telescope')),
            ],
        ),
    ]
